spring:
  application:
    name: sykun-mall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
server:
  port: 9999
  servlet:
    context-path: /sykun
logging:
  level:
    root: info
    com.sykun.baizhimall.service: debug
    com.sykun.baizhimall.dao: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1